
name: execucao CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'
            - run: npm install
            - run: npx mocha testes/trabalho-final.js

# os testes serão executados automaticamente a cada push ou pull request na branch `main` , que 
# é a branch principal do repositório.
